api_encryption_key: "YOUR_API_ENCRYPTION_KEY"
ota_password: "YOUR_OTA_PASSWORD"

JonS_Office_ssid: "JonS_Office"
JonS_Office_password: "YOUR_WIFI_PASSWORD"

Basement_II_ssid: "Basement II"
Basement_II_password: "YOUR_WIFI_PASSWORD"

Martin_Router_King_ssid: "Martin Router King"
Martin_Router_King_password: "YOUR_WIFI_PASSWORD"

Wifi_4_Kettwig_ssid: "Wifi 4 Kettwig"
Wifi_4_Kettwig_password: "YOUR_WIFI_PASSWORD"

wifi_ssid: "Basement II"
wifi_password: "YOUR_WIFI_PASSWORD"
